name: medusaPipeline
channels:
  - arthurvinx
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - annotate=1.0
  - binutils_impl_linux-64=2.35.1
  - binutils_linux-64=2.35
  - bioconductor-annotationdbi=1.52.0
  - bioconductor-biobase=2.50.0
  - bioconductor-biocgenerics=0.36.0
  - bioconductor-go.db=3.12.1
  - bioconductor-iranges=2.24.1
  - bioconductor-s4vectors=0.28.1
  - boost-cpp=1.74.0
  - bowtie2=2.4.3
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.12.5
  - cairo=1.16.0
  - certifi=2020.12.5
  - curl=7.76.1
  - cython=0.29.23
  - diamond=2.0.9
  - fastp=0.20.1
  - fastx_toolkit=0.0.14
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - fribidi=1.0.10
  - gcc_impl_linux-64=9.3.0
  - gcc_linux-64=9.3.0
  - gettext=0.19.8.1
  - gfortran_impl_linux-64=9.3.0
  - gfortran_linux-64=9.3.0
  - graphite2=1.3.13
  - gsl=2.6
  - gxx_impl_linux-64=9.3.0
  - gxx_linux-64=9.3.0
  - harfbuzz=2.8.1
  - hdf5=1.10.6
  - htslib=1.12
  - icu=68.1
  - jpeg=9d
  - kaiju=1.7.4
  - kernel-headers_linux-64=2.6.32
  - krb5=1.19.1
  - krona=2.8
  - ld_impl_linux-64=2.35.1
  - leveldb=1.23
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.76.1
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgcc-devel_linux-64=9.3.0
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libglib=2.68.2
  - libgomp=9.3.0
  - libgtextutils=0.7
  - libiconv=1.16
  - libidn2=2.3.1
  - liblapack=3.9.0
  - libnghttp2=1.43.0
  - libopenblas=0.3.15
  - libpng=1.6.37
  - libssh2=1.9.0
  - libstdcxx-devel_linux-64=9.3.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuuid=2.32.1
  - libwebp-base=1.2.0
  - libxcb=1.13
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - make=4.3
  - megahit=1.2.9
  - ncbi-ngs-sdk=2.11.0
  - ncurses=6.2
  - nose=1.3.7
  - openssl=1.1.1k
  - ossuuid=1.6.2
  - pango=1.48.4
  - pcre=8.44
  - pcre2=10.36
  - perl=5.26.2
  - perl-app-cpanminus=1.7044
  - perl-business-isbn=3.004
  - perl-business-isbn-data=20140910.003
  - perl-carp=1.38
  - perl-constant=1.33
  - perl-data-dumper=2.173
  - perl-encode=2.88
  - perl-exporter=5.72
  - perl-extutils-makemaker=7.36
  - perl-file-path=2.16
  - perl-file-temp=0.2304
  - perl-mime-base64=3.15
  - perl-parent=0.236
  - perl-uri=1.76
  - perl-xml-libxml=2.0132
  - perl-xml-namespacesupport=1.12
  - perl-xml-sax=1.02
  - perl-xml-sax-base=1.09
  - perl-xsloader=0.24
  - pigz=2.6
  - pip=21.1.1
  - pixman=0.40.0
  - plyvel=1.3.0
  - pthread-stubs=0.4
  - python=3.9.4
  - python_abi=3.9
  - r-assertthat=0.2.1
  - r-backports=1.2.1
  - r-base=4.0.5
  - r-bit=4.0.4
  - r-bit64=4.0.5
  - r-blob=1.2.1
  - r-cachem=1.0.5
  - r-cli=2.5.0
  - r-crayon=1.4.1
  - r-data.table=1.14.0
  - r-dbi=1.1.1
  - r-digest=0.6.27
  - r-dplyr=1.0.6
  - r-ellipsis=0.3.2
  - r-fansi=0.4.2
  - r-fastmap=1.1.0
  - r-generics=0.1.0
  - r-glue=1.4.2
  - r-lifecycle=1.0.0
  - r-magrittr=2.0.1
  - r-memoise=2.0.0
  - r-pillar=1.6.1
  - r-pkgconfig=2.0.3
  - r-plogr=0.2.0
  - r-purrr=0.3.4
  - r-r6=2.5.0
  - r-rcpp=1.0.6
  - r-rlang=0.4.11
  - r-rsqlite=2.2.5
  - r-tibble=3.1.2
  - r-tidyr=1.1.3
  - r-tidyselect=1.1.1
  - r-utf8=1.2.1
  - r-vctrs=0.3.8
  - r-zeallot=0.1.0
  - readline=8.1
  - samtools=1.12
  - sed=4.8
  - setuptools=49.6.0
  - snappy=1.1.8
  - sqlite=3.35.5
  - sra-tools=2.11.0
  - sysroot_linux-64=2.12
  - tbb=2020.2
  - tk=8.6.10
  - tktable=2.10
  - tzdata=2021a
  - wget=1.20.1
  - wheel=0.36.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.1
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
